.github/workflows/ci.yml

- Auto-update the extension version based on
- Release tag
- git describe
- Update CHANGELOG.md

Set extension version

---

.github/ISSUE_TEMPLATE/blocking_bug_report.yml
.github/workflows/ci.yml

N/A
- Removed x86 on Mac and arm64 on Windows target builds. We don't have pyOCD pyInstaller builds for those yet.

Remove target platforms without pyOCD builds

---

.github/workflows/tpip.yml
TPIP.md

N/A
- Change TPIP workflow to run as part of PRs rather than post commit to `main`. This shall work around the CI user not having (and not supposed to have) direct write access to `main`.

Run TPIP workflow in PRs for `main`

---

CHANGELOG.md
__mocks__/vscode.js
src/debug-configuration/gdbtarget-debug-tracker.test.ts
src/debug-configuration/gdbtarget-debug-tracker.ts
src/desktop/extension.ts

- #69 
- Add simple debug tracker that brings debug console to front when `onWillStartSession` is called.
- Note: Considering as temporary workaround, to request similar behavior from CDT GDB Adapter extension.

Biring debug console to front on debug session start

---

CHANGELOG.md
DEVELOPMENT.md
README.md
package.json

N/A
- Prepares 0.0.2 Pre-Release on GitHub

Prepare 0.0.2 Pre-Release

---

src/desktop/add-to-path.ts
src/desktop/builtin-tool-path.ts
src/desktop/extension.ts

- [#83 ](https://github.com/Open-CMSIS-Pack/vscode-cmsis-debugger/issues/83)
Created a function to add the executable pyOCD path to the PATH variable of only the vscode terminal

adding pyocd executable to PATH variable

---

src/debug-configuration/gdbtarget-configuration.ts
src/debug-configuration/subproviders/pyocd-configuration-provider.ts

- [#84](https://github.com/Open-CMSIS-Pack/vscode-cmsis-debugger/issues/84)
- a parameter with the name CMSIS_PACK_ROOT is added to the target.environment configuration for users to add their CMSIS_PACK_ROOT path
- if the user has CMSIS_PACK_ROOT set as a global environment variable, then it will be used instead by pyOCD

Adding CMSIS_PACK_ROOT handling by default for pyOCD

---

CHANGELOG.md
README.md
package.json

- closes #102 
- temporary docs update to deal with #101 (technical fix needs further investigation)
- prepares 0.1.0 release
- some readme rework
- known limitations and solutions section for problems most likely to be hit by early users
- changelog updates (ongoing)
- pulls in latest pyocd release

Docs updates and release preparations v0.1.0

---

src/desktop/add-to-path.ts

- #153 
- Uses `prepend` instead of `replace` env var collection mutator.
- Only updates mutator if path not already set from previous session (cleans up mutators from previous approach).
- This avoids the terminal to require a refresh on each workspace open.

Refine pyOCD path setting for terminals

---

package.json

- [#155 ](https://github.com/Open-CMSIS-Pack/vscode-cmsis-debugger/issues/155)
- default launch configuration given in the package.json, initcommands section, tbreak is used instead of break

changing default launch config initcommands to tbreak instead of break

---

package.json

- Loosely related to #96 
- Adds the same `cmsis`>`cbuildRunFile` setting to for J-LINK default configs as for pyOCD. This allows to extract and set the SVD file path for the Peripheral Inspector.
- Note that this doesn't add full `*.cbuild-run.yml` support for Segger J-LINK. Which might be perceived as confusing.
Requires #151 to be merged to show effect.

Add `cmsis`>`cbuildRunFile` setting to J-LINK default configs to configure Peripheral Inspector

---

CHANGELOG.md

- Closes #170 
- Replaces relative path to full docs MD files with new HTML docs link on the web.
- This does not resolve inclusion of HTML docs into extension!

Replace broken link in changelog

---

.github/markdown-link-check.jsonc
.github/markdownlint.json
.github/markdownlint.jsonc
.github/workflows/markdown.yml
CHANGELOG.md
DEVELOPMENT.md
README.md
SECURITY.md
docs/configure.md
docs/debug_views.md
docs/index.md
docs/setup.md
docs/tpip-header.md

- **This change introduces an automated Markdown linter and link checker job.**
The goal is to ensure that all changes to Markdown files follow consistent formatting standards and that any URLs included are valid and reachable. If any issues are detected, the workflow will fail and provide detailed output, highlighting the exact lines with errors along with clear error messages.

Markdown linter and link checker jobs

---

src/cbuild-run/__snapshots__/cbuild-run-reader.test.ts.snap
src/cbuild-run/cbuild-run-types.ts
test-data/simple.cbuild-run.yml

- Closes #219 
- Update cbuild-run interfaces and reader test data to new schema coming with [toolbox 2.9.0](https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/2.9.0/tools/projmgr/schemas/common.schema.json#/definitions/RunDebugDescType)

Update cbuild-run types to toolbox 2.9.0 schema

---

.github/workflows/ci.yml

- Need to have `content: write` permissions for release action

Fine grained permissions for release job

---

.github/workflows/ci.yml
.qlty/qlty.toml

- Migrated from code_climate to QLTY

Migrate from code_climate to QLTY

---

.github/workflows/ci.yml
CHANGELOG.md

Switch from pre-releases to full releases. But stay on `preview` status.
Technicality to include this extension properly into extension packs that are past the `pre-release` stage.

Remove pre-release flag from packaging

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/scorecard.yml
.github/workflows/tpip.yml

##Fix:
- Prevented irrelevant CI jobs from running when only documentation (`.md`) files are changed.
- Normalized line endings in `ci.yml` from CRLF to LF for consistency across environments.

Prevent workflows from running on doc-only changes

---

src/desktop/add-to-path.test.ts
src/desktop/add-to-path.ts
src/desktop/extension.ts

- [#337 ](https://github.com/Open-CMSIS-Pack/vscode-cmsis-debugger/issues/337)
- Refactored the function addPycdToPath to give us a chance of adding more built-in tools using the same method

Refactoring addPyocdToPath to make it useable for adding more built-in tools to the PATH variable

---

.github/workflows/ci.yml
CHANGELOG.md
TPIP.md
docs/third-party-licenses.json
package.json

N/A
- Preparations to create a pre-release for debug solution testing prior to 1.0.0 release.
- Includes pyOCD 0.38.0-pre0
- CHANGELOG updates as for 1.0.0 release (no `pre0` in version).
- TPIP updates for pyOCD 0.38.0-pre0 to keep CI happy.
No more planned changes in this release for 1.0.0. Work on CDT GDB adapter is ongoing.

1.0.0-pre0 Release Preparations

---

.github/workflows/ci.yml
.github/workflows/tpip.yml

- https://github.com/Open-CMSIS-Pack/vscode-cmsis-debugger/security/code-scanning/1
- https://github.com/Open-CMSIS-Pack/vscode-cmsis-debugger/security/code-scanning/6
- https://github.com/Open-CMSIS-Pack/vscode-cmsis-debugger/security/code-scanning/21
- Restore global permissions for all workflows to be only "contents: read" as suggested by best practices. Got changed with a recent PR.
- Disable "contents: write" for TPIP workflow until git push gets resurrected.
Other flagged security warnings had been dismissed as "won't fix" before. They can't be avoided to keep the needed level of CI automation.
@soumeh01 , curious if we can add ignore-comments to the workflows similar to our linters. Given we'll never change the workflows but issues can be re-raised.

Workflow permissions

---

CHANGELOG.md
src/cbuild-run/__snapshots__/cbuild-run-reader.test.ts.snap
src/cbuild-run/cbuild-run-reader.test.ts
src/cbuild-run/cbuild-run-reader.ts
src/debug-configuration/subproviders/base-configuration-provider.ts
src/debug-configuration/subproviders/generic-configuration-provider.test.ts
src/utils.test.ts
src/utils.ts
test-data/multi-core.cbuild-run.yml

- #439 
- Extracts Pname list from cbuild-run processors.
- Extracts Pname from debug config name. Unfortunately not much opportunity for config name validation due to free-form character of debug config names in templates.
- Select SVD file based on Pname match, otherwise use first and warn of more than one SVD file.

Extract Pname from debug config name to select correct SVD file
