- SECURITY.md
- Add initial security policy document
> Add initial security policy document

- .github/workflows/ci.yml
N/A
- Remove lines with CodeClimate badge links from README.md before building dist.
> Remove badges for dist (README.md)

- .github/workflows/ci.yml
N/A
- Quick fix to allow publishing pre-release to marketplace. Fine until reaching release quality. Then to review.
> Update CI to always package as pre-release

- CHANGELOG.md
- README.md
N/A
- Update changelog for upcoming release.
- Remove `CMSIS_PACK_ROOT` workaround from README.md.
> Prepare 0.0.3 Pre-Release

- CHANGELOG.md
- package.json
N/A
- Prepare changelog and package.json for 0.1.1 release.
- First-time updating versions manually before release to have the version captured also in source in the repo itself.
> Prepare 0.1.1 release

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- package.json
- yarn.lock
- Collection of dependabot updates
- #193 
- #194 
- #195 
- #196 
- #197
> Dependabot collection 2025wk18

- .github/workflows/ci.yml
- .github/workflows/scorecard.yml
- README.md
- Scorecard repo security check
> Added scorecard security check

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/markdown.yml
- .github/workflows/mkdocs.yml
- .github/workflows/scorecard.yml
- .github/workflows/tpip.yml
- The change addresses multiple security concerns
- Use of pinned actions
- Lift default permissions
- Concurrent run of workflows
should address a few of issues listed under https://github.com/Open-CMSIS-Pack/vscode-cmsis-debugger/security/code-scanning
> Addressing pinned dependencies, control permissions

- package.json
- yarn.lock
- #230 
- #231 
- #232 
- #233
> Dependabot collection 2025wk20

- CHANGELOG.md
- package.json
- N/A
- Bump included pyOCD version
- 0.2.0 release preparations (version, changelog, etc)
> Prepare 0.2.0 release

- .github/markdown-link-check.jsonc
- DEVELOPMENT.md
- package.json
- scripts/check-links.ts
- yarn.lock
- [#259](https://github.com/Open-CMSIS-Pack/vscode-cmsis-debugger/issues/259)
> Link checker and documentation updates

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/scorecard.yml
- package.json
- yarn.lock
- N/A
- #247 
- #248 
- #249 
- #250 
- #251 
- #252 
- #253 
- #254 
- #255 
- #256 
- #257
> Dependabot collection wk21

- .github/workflows/scorecard.yml
- package.json
- yarn.lock
- #296 
- #295 
- #293 
- #292 
- #291 
- #290 
- #281 
- #280 
- #277 
Note: #294 to be handled separately, breaks download scripts.
> Dependabot Updates wk23, 2025

- CHANGELOG.md
- README.md
- package.json
N/A
- Add Microsoft Serial Monitor extension to extension pack.
> Add Microsoft Serial Monitor extension to extension pack

- DEVELOPMENT.md
- package.json
- scripts/download-tools.ts
- yarn.lock
> Bump yargs to v18.x and fix incompatibilities

- CHANGELOG.md
- README.md
- package.json
- Fixes image links in README for patch release
> 0.3.1 Release Preparations

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/markdown.yml
- .github/workflows/scorecard.yml
- .github/workflows/tpip.yml
- package.json
- yarn.lock
N/A
Consolidated dependabot PRs
- #309 
- #310
- #311 
- #312 
- #319 
- #320 
- #321 
- #322 
- #323 
- #324 
- #325
> Dependabot wk25 2025

- CHANGELOG.md
- N/A
- Replaces outdated documentation links with documentation/README on VS Code marketplace.
> Replace outdated links in changelog

- .vscode/launch.json
- package.json
- scripts/download-tools.ts
- scripts/file-download.ts
- yarn.lock
-
- Downloads standalone gdb into tools folder
> Enhance download-tools script to fetch gdb

- CHANGELOG.md
- #337 
- Adds license change to CHANGELOG for transparency.
> Add license change to CHANGELOG

- LICENSE
N/A
- Added line breaks in LICENSE to fix MD rendering
> LICENSE fixup: line breaks

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/markdown.yml
- .github/workflows/scorecard.yml
- .github/workflows/tpip.yml
- TPIP.md
- docs/third-party-licenses.json
- package.json
- yarn.lock
N/A
- Updates TPIP docs: yaml 2.8.0
- #410 
- #411 
- #412 
- #413 
- #414 
- #415 
- @typescript-eslint/eslint-plugin 8.37.0
> Dependabot Collection

- .github/workflows/ci.yml
> Add extension package for Windows-on-Arm

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/markdown.yml
- .github/workflows/scorecard.yml
- .github/workflows/tpip.yml
- package.json
- yarn.lock
- #481 
- #480 
- #479
- #478 
- #477 
- #476 
- #475 
- #469 
- #463 
- #454 
- #452 
- #450 
- #448
> Dependency updates
